### ISSUE TITLE
Element order assumed in ul element

### ISSUE THREAD

**Issue by calcinai** [phindmarsh/alexa-wgtn-rubbish#1]
The parsing [on line 98 of wcc-rubbish.js](https://github.com/phindmarsh/alexa-wgtn-rubbish/blob/master/lib/wcc-rubbish.js#L98) assumes that the second item in the `ul` will be the recycling element.

Using a numeric offset in an unordered list seems unreliable, especially because the `try/catch` higher won't catch an undefined index.

**Comment by phindmarsh** [comment]
This issue is rubbish.

**Comment by calcinai** [comment]
Ruthless
